//! Linux Wayland IME backend.
//!
//! Uses zwp_input_method_v2 for keyboard interception and zwp_input_popup_surface_v2
//! for the candidate panel — a Wayland-native approach that never touches focus.
//! The panel is rendered via CPU rasterization (tiny-skia + cosmic-text) into a SHM buffer.

use std::{
    fs::File,
    io::Write,
    os::fd::{AsFd, AsRawFd, FromRawFd, OwnedFd},
    path::PathBuf,
    sync::{Arc, RwLock},
};

use cosmic_text::{Attrs, Buffer, FontSystem, Metrics, Shaping, SwashCache, SwashContent};
use keytao_core::{default_shared_data_dir, default_user_data_dir, deploy, Engine, ImeState};
use tauri::{AppHandle, Emitter};
use tiny_skia::{Color, FillRule, Paint, PathBuilder, Pixmap, Rect, Stroke, Transform};
use wayland_client::{
    delegate_noop,
    globals::{registry_queue_init, GlobalListContents},
    protocol::{
        wl_buffer::WlBuffer,
        wl_compositor::WlCompositor,
        wl_keyboard::{self, WlKeyboard},
        wl_registry,
        wl_seat::WlSeat,
        wl_shm::{self, WlShm},
        wl_shm_pool::WlShmPool,
        wl_surface::WlSurface,
    },
    Connection, Dispatch, QueueHandle, WEnum,
};
use wayland_protocols_misc::zwp_input_method_v2::client::{
    zwp_input_method_keyboard_grab_v2::{self, ZwpInputMethodKeyboardGrabV2},
    zwp_input_method_manager_v2::ZwpInputMethodManagerV2,
    zwp_input_method_v2::{self, ZwpInputMethodV2},
    zwp_input_popup_surface_v2::{self, ZwpInputPopupSurfaceV2},
};
use wayland_protocols_misc::zwp_virtual_keyboard_v1::client::{
    zwp_virtual_keyboard_manager_v1::ZwpVirtualKeyboardManagerV1,
    zwp_virtual_keyboard_v1::ZwpVirtualKeyboardV1,
};
use xkbcommon::xkb;

pub const RELEASE_MASK: u32 = 1 << 30;

const MOD_SHIFT: u32 = 0x0001;
const MOD_CONTROL: u32 = 0x0004;
const MOD_MOD1: u32 = 0x0008;

const RADIUS: f32 = 8.0;
const H_PAD: f32 = 10.0;
const CAND_H_PAD: f32 = 9.0;
const MIN_CELL_W: f32 = 30.0;
const FONT_SIZE: f32 = 16.0;
const KEY_SIZE: f32 = 11.0;
const COMMENT_SIZE: f32 = 12.0;
const PREEDIT_H: f32 = 26.0;
const CELL_H: f32 = 32.0;
const MAX_COLS: usize = 9;

/// Shared state read by the tray icon and written by the IME thread.
pub struct TrayShared {
    pub schema_name: String,
    pub redeploy_requested: bool,
}

pub type TrayArc = Arc<RwLock<TrayShared>>;

const DEFAULT_CUSTOM_YAML: &str = r#"# default.custom.yaml — generated by keytao-installer
patch:
  schema_list:
    - schema: keytao
    - schema: keytao-dz
    - schema: keytao-bj
  menu:
    page_size: 6
  ascii_composer/good_old_caps_lock: true
  ascii_composer/switch_key:
    Caps_Lock: commit_text
    Shift_L: commit_text
"#;

fn preferred_user_dir() -> Option<PathBuf> {
    let fcitx5 = dirs::data_local_dir()?.join("fcitx5/rime");
    if fcitx5
        .join("build")
        .join("keytao.extended.table.bin")
        .exists()
    {
        return Some(fcitx5);
    }
    default_user_data_dir()
}

fn ensure_default_custom_yaml(user_dir: &std::path::Path) -> Result<(), String> {
    let target = user_dir.join("default.custom.yaml");
    if target.exists() {
        return Ok(());
    }
    std::fs::create_dir_all(user_dir).map_err(|e| format!("create user dir: {e}"))?;
    std::fs::write(&target, DEFAULT_CUSTOM_YAML)
        .map_err(|e| format!("write default.custom.yaml: {e}"))?;
    Ok(())
}

pub fn spawn(app: AppHandle, tray: TrayArc) {
    std::thread::Builder::new()
        .name("wayland-ime".into())
        .spawn(move || {
            if let Err(e) = init_and_run(app, tray) {
                tracing::error!("Wayland IME thread exited: {e}");
            }
        })
        .expect("spawn wayland-ime thread");
}

fn init_and_run(app: AppHandle, tray: TrayArc) -> Result<(), Box<dyn std::error::Error>> {
    let user_dir = preferred_user_dir().ok_or("cannot determine keytao data directory")?;
    let user = user_dir.to_string_lossy().into_owned();
    let shared = default_shared_data_dir();
    tracing::info!("Rime user_dir={user} shared_dir={shared}");
    ensure_default_custom_yaml(&user_dir)
        .map_err(|e| format!("ensure_default_custom_yaml: {e}"))?;
    deploy(user, shared)?;
    let engine = Engine::new()?;
    tracing::info!("librime initialised");
    run_wayland(engine, tray, app)
}

fn run_wayland(
    engine: Engine,
    tray: TrayArc,
    app: AppHandle,
) -> Result<(), Box<dyn std::error::Error>> {
    let conn = Connection::connect_to_env()?;
    let (globals, mut queue) = registry_queue_init::<App>(&conn)?;
    let qh = queue.handle();

    let compositor: WlCompositor = globals.bind(&qh, 1..=4, ())?;
    let shm: WlShm = globals.bind(&qh, 1..=1, ())?;
    let seat: WlSeat = globals.bind(&qh, 1..=7, ())?;
    let ime_manager: ZwpInputMethodManagerV2 = globals
        .bind(&qh, 1..=1, ())
        .map_err(|_| "compositor does not advertise zwp_input_method_manager_v2")?;
    let vk_manager: Option<ZwpVirtualKeyboardManagerV1> = globals.bind(&qh, 1..=1, ()).ok();

    let font_system = FontSystem::new();
    let swash_cache = SwashCache::new();

    let mut state = App {
        engine,
        font_system,
        swash_cache,
        compositor,
        shm,
        seat,
        ime_manager,
        input_method: None,
        keyboard_grab: None,
        serial: 0,
        active: false,
        xkb_context: xkb::Context::new(xkb::CONTEXT_NO_FLAGS),
        xkb_keymap: None,
        xkb_state: None,
        mods: 0,
        vk: None,
        popup_surface: None,
        popup_proxy: None,
        popup_buffer: None,
        tray,
        app_handle: app,
        ascii_mode: false,
        mode_hint_until: None,
    };

    // Create virtual keyboard for forwarding keys the IME doesn't consume.
    if let Some(mgr) = vk_manager {
        let vk = mgr.create_virtual_keyboard(&state.seat, &qh, ());
        state.vk = Some(vk);
    }

    state.setup_ime(&qh);
    queue.roundtrip(&mut state)?;

    tracing::info!("Wayland IME running (native popup surface)");
    loop {
        // Auto-hide mode hint after 3 seconds.
        if state
            .mode_hint_until
            .map_or(false, |t| std::time::Instant::now() >= t)
        {
            state.mode_hint_until = None;
            if state.popup_surface.is_some() {
                let empty = ImeState::empty();
                state.render_panel(&empty, &qh);
            }
        }

        // Flush pending requests to the Wayland server.
        queue.flush()?;

        // Poll: 100ms timeout while hint is active so the timer check fires promptly.
        let timeout_ms: i32 = if state.mode_hint_until.is_some() {
            100
        } else {
            -1
        };
        let raw_fd = conn.as_fd().as_raw_fd();
        let mut pfd = libc::pollfd {
            fd: raw_fd,
            events: libc::POLLIN,
            revents: 0,
        };
        let ready = unsafe { libc::poll(&mut pfd as *mut libc::pollfd, 1, timeout_ms) };
        if ready > 0 {
            queue.blocking_dispatch(&mut state)?;
        }
    }
}

struct App {
    engine: Engine,
    font_system: FontSystem,
    swash_cache: SwashCache,
    compositor: WlCompositor,
    shm: WlShm,
    seat: WlSeat,
    ime_manager: ZwpInputMethodManagerV2,
    input_method: Option<ZwpInputMethodV2>,
    keyboard_grab: Option<ZwpInputMethodKeyboardGrabV2>,
    serial: u32,
    active: bool,
    xkb_context: xkb::Context,
    xkb_keymap: Option<xkb::Keymap>,
    xkb_state: Option<xkb::State>,
    mods: u32,
    vk: Option<ZwpVirtualKeyboardV1>,
    popup_surface: Option<WlSurface>,
    popup_proxy: Option<ZwpInputPopupSurfaceV2>,
    popup_buffer: Option<WlBuffer>,
    tray: TrayArc,
    app_handle: AppHandle,
    ascii_mode: bool,
    mode_hint_until: Option<std::time::Instant>,
}

impl App {
    fn setup_ime(&mut self, qh: &QueueHandle<Self>) {
        let im = self.ime_manager.get_input_method(&self.seat, qh, ());
        self.input_method = Some(im);
    }

    fn create_popup(&mut self, qh: &QueueHandle<Self>) {
        let surface = self.compositor.create_surface(qh, ());
        let proxy = self
            .input_method
            .as_ref()
            .unwrap()
            .get_input_popup_surface(&surface, qh, ());
        // 1×1 transparent buffer to make surface valid
        let buf = self.upload_pixels(&[0u8; 4], 1, 1, qh);
        surface.attach(buf.as_ref(), 0, 0);
        surface.damage(0, 0, 1, 1);
        surface.commit();
        self.popup_buffer = buf;
        self.popup_surface = Some(surface);
        self.popup_proxy = Some(proxy);
    }

    fn destroy_popup(&mut self) {
        self.popup_buffer.take();
        if let Some(p) = self.popup_proxy.take() {
            p.destroy();
        }
        if let Some(s) = self.popup_surface.take() {
            s.destroy();
        }
    }

    fn upload_pixels(
        &self,
        bgra: &[u8],
        w: i32,
        h: i32,
        qh: &QueueHandle<Self>,
    ) -> Option<WlBuffer> {
        let stride = w * 4;
        let mut tmp = memfd().ok()?;
        tmp.write_all(bgra).ok()?;
        let pool = self.shm.create_pool(tmp.as_fd(), bgra.len() as i32, qh, ());
        let buf = pool.create_buffer(0, w, h, stride, wl_shm::Format::Argb8888, qh, ());
        pool.destroy();
        Some(buf)
    }

    fn render_panel(&mut self, ime: &ImeState, qh: &QueueHandle<Self>) {
        let has_content = !ime.preedit.is_empty() || !ime.candidates.is_empty();
        let show_mode_hint = self
            .mode_hint_until
            .map_or(false, |t| std::time::Instant::now() < t);

        let Some(surface) = &self.popup_surface else {
            return;
        };

        if !has_content && !show_mode_hint {
            surface.attach(None, 0, 0);
            surface.commit();
            self.popup_buffer.take();
            return;
        }

        // Mode indicator: pill-shaped floating badge.
        if !has_content && show_mode_hint {
            let label = if self.ascii_mode { "英" } else { "中" };
            let lw = text_width(&mut self.font_system, label, FONT_SIZE);
            let pad_h = 14.0f32;
            let w = (lw + pad_h * 2.0).ceil() as i32;
            let h = (FONT_SIZE * 1.4 + 8.0).ceil() as i32;
            let mut pixmap = match Pixmap::new(w as u32, h as u32) {
                Some(p) => p,
                None => return,
            };
            if let Some(path) =
                rounded_rect_path(0.5, 0.5, w as f32 - 1.0, h as f32 - 1.0, h as f32 * 0.45)
            {
                let bg = if self.ascii_mode {
                    Color::from_rgba8(72, 32, 12, 235)
                } else {
                    Color::from_rgba8(16, 48, 88, 235)
                };
                let mut paint = Paint::default();
                paint.set_color(bg);
                paint.anti_alias = true;
                pixmap.fill_path(
                    &path,
                    &paint,
                    FillRule::Winding,
                    Transform::identity(),
                    None,
                );
                let border = if self.ascii_mode {
                    Color::from_rgba8(180, 100, 40, 120)
                } else {
                    Color::from_rgba8(60, 140, 220, 120)
                };
                paint.set_color(border);
                let mut stroke = Stroke::default();
                stroke.width = 1.0;
                pixmap.stroke_path(&path, &paint, &stroke, Transform::identity(), None);
            }
            let fg = if self.ascii_mode {
                Color::from_rgba8(255, 175, 70, 255)
            } else {
                Color::from_rgba8(100, 205, 255, 255)
            };
            let baseline_y = (h as f32 + FONT_SIZE) * 0.5 - 2.0;
            draw_text(
                &mut self.font_system,
                &mut self.swash_cache,
                &mut pixmap,
                label,
                pad_h,
                baseline_y,
                FONT_SIZE,
                fg,
            );
            commit_pixmap(
                pixmap,
                self.popup_surface.as_ref().unwrap(),
                &mut self.popup_buffer,
                &self.shm,
                w,
                h,
                qh,
            );
            return;
        }

        // ── Candidate panel ───────────────────────────────────────────────────

        let n = ime.candidates.len().min(MAX_COLS);
        let select_keys = ime.select_keys.as_deref().unwrap_or("1234567890");
        let has_preedit = !ime.preedit.is_empty();

        // Measure each candidate column (key_label + cand_text + optional comment).
        let mut col_widths: Vec<f32> = Vec::with_capacity(n);
        for (i, c) in ime.candidates.iter().take(n).enumerate() {
            let key = select_keys.chars().nth(i).unwrap_or(' ');
            let key_str = format!("{key}.");
            let comment = c.comment.as_deref().unwrap_or("");
            let key_w = text_width(&mut self.font_system, &key_str, KEY_SIZE);
            let cand_w = text_width(&mut self.font_system, &c.text, FONT_SIZE);
            let comm_w = if comment.is_empty() {
                0.0
            } else {
                4.0 + text_width(&mut self.font_system, comment, COMMENT_SIZE)
            };
            col_widths.push((key_w + 3.0 + cand_w + comm_w + CAND_H_PAD * 2.0).max(MIN_CELL_W));
        }

        let preedit_w = if has_preedit {
            text_width(&mut self.font_system, &ime.preedit, FONT_SIZE) + H_PAD * 2.0
        } else {
            0.0
        };
        let cands_w: f32 = col_widths.iter().sum::<f32>();
        let panel_w = preedit_w.max(cands_w).max(60.0).ceil() as i32;
        let panel_h = ((if has_preedit { PREEDIT_H } else { 0.0 })
            + (if n > 0 { CELL_H } else { 0.0 }))
        .ceil() as i32;

        let mut pixmap = match Pixmap::new(panel_w as u32, panel_h as u32) {
            Some(p) => p,
            None => return,
        };

        // Background + border (rounded).
        if let Some(path) =
            rounded_rect_path(0.5, 0.5, panel_w as f32 - 1.0, panel_h as f32 - 1.0, RADIUS)
        {
            let mut paint = Paint::default();
            paint.set_color(Color::from_rgba8(18, 20, 28, 240));
            paint.anti_alias = true;
            pixmap.fill_path(
                &path,
                &paint,
                FillRule::Winding,
                Transform::identity(),
                None,
            );
            paint.set_color(Color::from_rgba8(55, 65, 95, 160));
            let mut stroke = Stroke::default();
            stroke.width = 1.0;
            pixmap.stroke_path(&path, &paint, &stroke, Transform::identity(), None);
        }

        // Preedit row.
        if has_preedit {
            let baseline_y = (PREEDIT_H + FONT_SIZE) * 0.5 - 2.0;
            draw_text(
                &mut self.font_system,
                &mut self.swash_cache,
                &mut pixmap,
                &ime.preedit,
                H_PAD,
                baseline_y,
                FONT_SIZE,
                Color::from_rgba8(140, 210, 255, 255),
            );
            // Blinking cursor bar (spans ascent + descent).
            let cur_byte = ime.cursor.min(ime.preedit.len());
            let cx = H_PAD + text_width(&mut self.font_system, &ime.preedit[..cur_byte], FONT_SIZE);
            fill_rect(
                &mut pixmap,
                cx,
                baseline_y - FONT_SIZE * 0.82,
                1.5,
                FONT_SIZE * 1.0,
                Color::from_rgba8(140, 210, 255, 210),
            );
            // Separator between preedit and candidates.
            fill_rect(
                &mut pixmap,
                RADIUS,
                PREEDIT_H - 1.0,
                panel_w as f32 - RADIUS * 2.0,
                1.0,
                Color::from_rgba8(48, 58, 82, 200),
            );
        }

        // Candidates row.
        if n > 0 {
            let row_top = if has_preedit { PREEDIT_H } else { 0.0 };
            // All text shares one baseline; smaller sizes sit at same baseline as FONT_SIZE text.
            // baseline shared by all text in this row
            let baseline_y = row_top + (CELL_H + FONT_SIZE) * 0.5 - 3.0;

            let mut x_off = 0.0f32;
            for (i, cand) in ime.candidates.iter().take(n).enumerate() {
                let is_sel = i == 0;
                let key = select_keys.chars().nth(i).unwrap_or(' ');
                let key_str = format!("{key}.");
                let comment = cand.comment.as_deref().unwrap_or("");

                // Rounded highlight for selected candidate.
                if is_sel {
                    if let Some(path) = rounded_rect_path(
                        x_off + 3.0,
                        row_top + 3.0,
                        col_widths[i] - 6.0,
                        CELL_H - 6.0,
                        5.0,
                    ) {
                        let mut paint = Paint::default();
                        paint.set_color(Color::from_rgba8(42, 55, 88, 215));
                        paint.anti_alias = true;
                        pixmap.fill_path(
                            &path,
                            &paint,
                            FillRule::Winding,
                            Transform::identity(),
                            None,
                        );
                    }
                }

                let cx = x_off + CAND_H_PAD;

                // Key label (small, dimmed) — same baseline as candidate text.
                let key_w = text_width(&mut self.font_system, &key_str, KEY_SIZE);
                draw_text(
                    &mut self.font_system,
                    &mut self.swash_cache,
                    &mut pixmap,
                    &key_str,
                    cx,
                    baseline_y,
                    KEY_SIZE,
                    if is_sel {
                        Color::from_rgba8(90, 145, 215, 200)
                    } else {
                        Color::from_rgba8(70, 80, 105, 175)
                    },
                );

                // Candidate text.
                let cand_w = text_width(&mut self.font_system, &cand.text, FONT_SIZE);
                draw_text(
                    &mut self.font_system,
                    &mut self.swash_cache,
                    &mut pixmap,
                    &cand.text,
                    cx + key_w + 3.0,
                    baseline_y,
                    FONT_SIZE,
                    if is_sel {
                        Color::from_rgba8(240, 245, 255, 255)
                    } else {
                        Color::from_rgba8(190, 200, 220, 255)
                    },
                );

                // Comment (small, right of candidate) — same baseline.
                if !comment.is_empty() {
                    draw_text(
                        &mut self.font_system,
                        &mut self.swash_cache,
                        &mut pixmap,
                        comment,
                        cx + key_w + 3.0 + cand_w + 4.0,
                        baseline_y,
                        COMMENT_SIZE,
                        Color::from_rgba8(90, 120, 165, 195),
                    );
                }

                // Thin divider between candidates (skip last).
                if i + 1 < n {
                    fill_rect(
                        &mut pixmap,
                        x_off + col_widths[i] - 0.5,
                        row_top + 8.0,
                        1.0,
                        CELL_H - 16.0,
                        Color::from_rgba8(42, 52, 72, 130),
                    );
                }

                x_off += col_widths[i];
            }
        }

        commit_pixmap(
            pixmap,
            self.popup_surface.as_ref().unwrap(),
            &mut self.popup_buffer,
            &self.shm,
            panel_w,
            panel_h,
            qh,
        );
    }

    fn handle_key_press(&mut self, evdev_key: u32, time: u32, qh: &QueueHandle<Self>) {
        let keycode = evdev_key + 8; // XKB keycode = evdev + 8
        let keysym = self
            .xkb_state
            .as_ref()
            .map(|s| s.key_get_one_sym(xkb::Keycode::from(keycode)))
            .unwrap_or(xkb::Keysym::from(xkb::keysyms::KEY_NoSymbol));
        let sym_raw: u32 = keysym.into();

        if sym_raw == xkb::keysyms::KEY_NoSymbol {
            return;
        }

        // For modifier keys themselves, strip their own bit from mods so rime sees
        // them as standalone presses, not "modifier held while pressing itself".
        let effective_mods = match sym_raw {
            s if s == xkb::keysyms::KEY_Shift_L || s == xkb::keysyms::KEY_Shift_R => {
                self.mods & !MOD_SHIFT
            }
            s if s == xkb::keysyms::KEY_Control_L || s == xkb::keysyms::KEY_Control_R => {
                self.mods & !MOD_CONTROL
            }
            s if s == xkb::keysyms::KEY_Alt_L || s == xkb::keysyms::KEY_Alt_R => {
                self.mods & !MOD_MOD1
            }
            _ => self.mods,
        };

        let ime_state = self.engine.process_key(sym_raw, effective_mods);
        let Some(im) = &self.input_method else { return };

        let consumed = ime_state.committed.is_some()
            || !ime_state.preedit.is_empty()
            || !ime_state.candidates.is_empty();

        if consumed {
            // Update tray schema name when IME state changes.
            if let Ok(mut tray) = self.tray.write() {
                let name = self.engine.current_schema_name();
                if tray.schema_name != name {
                    tray.schema_name = name.clone();
                    let _ = self.app_handle.emit("schema-changed", name);
                }
                // Check if redeploy was requested via tray.
                if tray.redeploy_requested {
                    tray.redeploy_requested = false;
                    drop(tray);
                    let user_dir = preferred_user_dir();
                    let user = user_dir
                        .as_deref()
                        .and_then(|p: &std::path::Path| p.to_str())
                        .unwrap_or("")
                        .to_string();
                    let shared = default_shared_data_dir();
                    if let Err(e) = deploy(user, shared) {
                        tracing::error!("redeploy failed: {e}");
                    } else {
                        tracing::info!("redeployed via tray");
                    }
                }
            }
            if let Some(committed) = &ime_state.committed {
                im.commit_string(committed.clone());
            }
            let preedit = ime_state.preedit.clone();
            let len = preedit.len() as i32;
            im.set_preedit_string(preedit, len, len);
            im.commit(self.serial);
            self.render_panel(&ime_state, qh);
        } else {
            let empty = ImeState::empty();
            self.render_panel(&empty, qh);
            // Forward unconsumed key to the application via virtual keyboard.
            self.forward_raw_key(evdev_key, time);
        }
    }

    fn handle_key_release(&mut self, evdev_key: u32, time: u32, qh: &QueueHandle<Self>) {
        let keycode = evdev_key + 8;
        let keysym = self
            .xkb_state
            .as_ref()
            .map(|s| s.key_get_one_sym(xkb::Keycode::from(keycode)))
            .unwrap_or(xkb::Keysym::from(xkb::keysyms::KEY_NoSymbol));
        let sym_raw: u32 = keysym.into();

        // Shift release must reach rime so it can trigger CN/EN mode toggle.
        if sym_raw == xkb::keysyms::KEY_Shift_L || sym_raw == xkb::keysyms::KEY_Shift_R {
            // Pass as release (kReleaseMask) with no other modifiers.
            self.engine.process_key(sym_raw, RELEASE_MASK);
            // Check if ascii_mode changed and show a brief mode indicator.
            let new_ascii = self.engine.is_ascii_mode();
            if new_ascii != self.ascii_mode {
                self.ascii_mode = new_ascii;
                self.mode_hint_until =
                    Some(std::time::Instant::now() + std::time::Duration::from_secs(3));
                // Render mode hint immediately.
                let empty = ImeState::empty();
                self.render_panel(&empty, qh);
            }
        } else {
            // Forward all other key releases via virtual keyboard.
            self.forward_raw_key_release(evdev_key, time);
        }
    }

    fn forward_raw_key(&self, evdev_key: u32, time: u32) {
        if let Some(vk) = &self.vk {
            vk.key(time, evdev_key, 1);
        }
    }

    fn forward_raw_key_release(&self, evdev_key: u32, time: u32) {
        if let Some(vk) = &self.vk {
            vk.key(time, evdev_key, 0);
        }
    }
}

fn rounded_rect_path(x: f32, y: f32, w: f32, h: f32, r: f32) -> Option<tiny_skia::Path> {
    let r = r.min(w * 0.5).min(h * 0.5);
    // Cubic bezier approximation for a quarter circle.
    let k = r * 0.5523;
    let mut pb = PathBuilder::new();
    pb.move_to(x + r, y);
    pb.line_to(x + w - r, y);
    pb.cubic_to(x + w - r + k, y, x + w, y + r - k, x + w, y + r);
    pb.line_to(x + w, y + h - r);
    pb.cubic_to(x + w, y + h - r + k, x + w - r + k, y + h, x + w - r, y + h);
    pb.line_to(x + r, y + h);
    pb.cubic_to(x + r - k, y + h, x, y + h - r + k, x, y + h - r);
    pb.line_to(x, y + r);
    pb.cubic_to(x, y + r - k, x + r - k, y, x + r, y);
    pb.close();
    pb.finish()
}

fn commit_pixmap(
    pixmap: Pixmap,
    surface: &WlSurface,
    popup_buffer: &mut Option<WlBuffer>,
    shm: &WlShm,
    w: i32,
    h: i32,
    qh: &QueueHandle<App>,
) {
    let stride = w * 4;
    let mut tmp = match memfd() {
        Ok(f) => f,
        Err(_) => return,
    };
    // Convert RGBA premultiplied → BGRA for wl_shm ARGB8888.
    let mut bgra = vec![0u8; (w * h * 4) as usize];
    for (i, px) in pixmap.pixels().iter().enumerate() {
        let b = i * 4;
        bgra[b] = px.blue();
        bgra[b + 1] = px.green();
        bgra[b + 2] = px.red();
        bgra[b + 3] = px.alpha();
    }
    if tmp.write_all(&bgra).is_err() {
        return;
    }
    let pool = shm.create_pool(tmp.as_fd(), bgra.len() as i32, qh, ());
    let buf = pool.create_buffer(0, w, h, stride, wl_shm::Format::Argb8888, qh, ());
    pool.destroy();
    surface.attach(Some(&buf), 0, 0);
    surface.damage(0, 0, w, h);
    surface.commit();
    *popup_buffer = Some(buf);
}

fn text_width(font_system: &mut FontSystem, text: &str, size: f32) -> f32 {
    let metrics = Metrics::new(size, size * 1.2);
    let mut buffer = Buffer::new(font_system, metrics);
    buffer.set_size(font_system, None, None);
    buffer.set_text(font_system, text, Attrs::new(), Shaping::Advanced);
    buffer.shape_until_scroll(font_system, false);
    buffer
        .layout_runs()
        .flat_map(|run| run.glyphs.iter())
        .map(|g| g.w)
        .sum()
}

fn draw_text(
    font_system: &mut FontSystem,
    swash_cache: &mut SwashCache,
    pixmap: &mut Pixmap,
    text: &str,
    x: f32,
    baseline_y: f32,
    size: f32,
    color: Color,
) {
    let metrics = Metrics::new(size, size * 1.2);
    let mut buffer = Buffer::new(font_system, metrics);
    buffer.set_size(font_system, None, None);
    buffer.set_text(font_system, text, Attrs::new(), Shaping::Advanced);
    buffer.shape_until_scroll(font_system, false);

    let pw = pixmap.width() as i32;
    let ph = pixmap.height() as i32;
    let pixels = pixmap.pixels_mut();

    let [cr, cg, cb, _] = [
        (color.red() * 255.0) as u8,
        (color.green() * 255.0) as u8,
        (color.blue() * 255.0) as u8,
        (color.alpha() * 255.0) as u8,
    ];

    for run in buffer.layout_runs() {
        // In a single-line buffer, LayoutGlyph.y == 0 (y-offset relative to hitbox).
        // Passing baseline_y as origin.1 makes phy.y == baseline_y in pixmap space.
        let _ = run; // line_y not needed
        for glyph in run.glyphs.iter() {
            let phy = glyph.physical((x, baseline_y), 1.0);
            let Some(image) = swash_cache.get_image(font_system, phy.cache_key) else {
                continue;
            };
            let img_x = phy.x + image.placement.left;
            let img_y = phy.y - image.placement.top;
            let iw = image.placement.width as i32;
            let ih = image.placement.height as i32;

            match image.content {
                SwashContent::Mask => {
                    for row in 0..ih {
                        for col in 0..iw {
                            let alpha = image.data[(row * iw + col) as usize];
                            if alpha == 0 {
                                continue;
                            }
                            let px = img_x + col;
                            let py = img_y + row;
                            if px < 0 || py < 0 || px >= pw || py >= ph {
                                continue;
                            }
                            if let Some(p) = pixels.get_mut((py * pw + px) as usize) {
                                let a = alpha as f32 / 255.0;
                                let ea = p.alpha() as f32 / 255.0;
                                let oa = a + ea * (1.0 - a);
                                if oa > 0.0 {
                                    let r = ((cr as f32 / 255.0 * a
                                        + p.red() as f32 / 255.0 * ea * (1.0 - a))
                                        / oa
                                        * 255.0) as u8;
                                    let g = ((cg as f32 / 255.0 * a
                                        + p.green() as f32 / 255.0 * ea * (1.0 - a))
                                        / oa
                                        * 255.0) as u8;
                                    let b = ((cb as f32 / 255.0 * a
                                        + p.blue() as f32 / 255.0 * ea * (1.0 - a))
                                        / oa
                                        * 255.0) as u8;
                                    if let Some(out) = tiny_skia::PremultipliedColorU8::from_rgba(
                                        r,
                                        g,
                                        b,
                                        (oa * 255.0) as u8,
                                    ) {
                                        *p = out;
                                    }
                                }
                            }
                        }
                    }
                }
                SwashContent::Color => {
                    // RGBA color bitmap (emoji): blit directly, ignoring `color` tint.
                    for row in 0..ih {
                        for col in 0..iw {
                            let base = ((row * iw + col) * 4) as usize;
                            if base + 3 >= image.data.len() {
                                continue;
                            }
                            let [sr, sg, sb, sa] = [
                                image.data[base],
                                image.data[base + 1],
                                image.data[base + 2],
                                image.data[base + 3],
                            ];
                            if sa == 0 {
                                continue;
                            }
                            let px = img_x + col;
                            let py = img_y + row;
                            if px < 0 || py < 0 || px >= pw || py >= ph {
                                continue;
                            }
                            if let Some(p) = pixels.get_mut((py * pw + px) as usize) {
                                let a = sa as f32 / 255.0;
                                let ea = p.alpha() as f32 / 255.0;
                                let oa = a + ea * (1.0 - a);
                                if oa > 0.0 {
                                    let r = ((sr as f32 / 255.0 * a
                                        + p.red() as f32 / 255.0 * ea * (1.0 - a))
                                        / oa
                                        * 255.0) as u8;
                                    let g = ((sg as f32 / 255.0 * a
                                        + p.green() as f32 / 255.0 * ea * (1.0 - a))
                                        / oa
                                        * 255.0) as u8;
                                    let b = ((sb as f32 / 255.0 * a
                                        + p.blue() as f32 / 255.0 * ea * (1.0 - a))
                                        / oa
                                        * 255.0) as u8;
                                    if let Some(out) = tiny_skia::PremultipliedColorU8::from_rgba(
                                        r,
                                        g,
                                        b,
                                        (oa * 255.0) as u8,
                                    ) {
                                        *p = out;
                                    }
                                }
                            }
                        }
                    }
                }
                SwashContent::SubpixelMask => {}
            }
        }
    }
}

fn fill_rect(pixmap: &mut Pixmap, x: f32, y: f32, w: f32, h: f32, color: Color) {
    let mut paint = Paint::default();
    paint.set_color(color);
    paint.anti_alias = false;
    if let Some(rect) = Rect::from_xywh(x, y, w, h) {
        pixmap.fill_rect(rect, &paint, Transform::identity(), None);
    }
}

impl Dispatch<wl_registry::WlRegistry, GlobalListContents> for App {
    fn event(
        _s: &mut Self,
        _r: &wl_registry::WlRegistry,
        _e: wl_registry::Event,
        _d: &GlobalListContents,
        _c: &Connection,
        _q: &QueueHandle<Self>,
    ) {
    }
}

impl Dispatch<ZwpInputMethodV2, ()> for App {
    fn event(
        state: &mut Self,
        proxy: &ZwpInputMethodV2,
        event: zwp_input_method_v2::Event,
        _: &(),
        _conn: &Connection,
        qh: &QueueHandle<Self>,
    ) {
        match event {
            zwp_input_method_v2::Event::Activate => {
                state.active = true;
                state.keyboard_grab = Some(proxy.grab_keyboard(qh, ()));
                state.create_popup(qh);
                tracing::debug!("IME activated");
            }
            zwp_input_method_v2::Event::Deactivate => {
                state.active = false;
                state.keyboard_grab.take();
                state.engine.reset();
                state.destroy_popup();
                tracing::debug!("IME deactivated");
            }
            zwp_input_method_v2::Event::Done => {
                state.serial = state.serial.wrapping_add(1);
            }
            zwp_input_method_v2::Event::Unavailable => {
                tracing::error!("input method unavailable — another IME may be running");
            }
            _ => {}
        }
    }
}

impl Dispatch<ZwpInputMethodKeyboardGrabV2, ()> for App {
    fn event(
        state: &mut Self,
        _proxy: &ZwpInputMethodKeyboardGrabV2,
        event: zwp_input_method_keyboard_grab_v2::Event,
        _: &(),
        _conn: &Connection,
        qh: &QueueHandle<Self>,
    ) {
        match event {
            zwp_input_method_keyboard_grab_v2::Event::Keymap { format, fd, size } => {
                if format != WEnum::Value(wl_keyboard::KeymapFormat::XkbV1) {
                    return;
                }
                // Forward keymap to virtual keyboard so it can process key events correctly.
                if let Some(vk) = &state.vk {
                    // dup fd so both VK and xkb can use it independently
                    let dup_fd = unsafe { libc::dup(fd.as_raw_fd()) };
                    if dup_fd >= 0 {
                        let owned = unsafe { std::os::unix::io::OwnedFd::from_raw_fd(dup_fd) };
                        vk.keymap(wl_keyboard::KeymapFormat::XkbV1 as u32, owned.as_fd(), size);
                    }
                }
                let Ok(mmap) = (unsafe {
                    memmap2::MmapOptions::new()
                        .len(size as usize)
                        .map_raw_read_only(&fd)
                }) else {
                    return;
                };
                let s = unsafe {
                    let bytes = std::slice::from_raw_parts(mmap.as_ptr(), size as usize - 1);
                    std::str::from_utf8_unchecked(bytes).to_string()
                };
                if let Some(km) = xkb::Keymap::new_from_string(
                    &state.xkb_context,
                    s,
                    xkb::KEYMAP_FORMAT_TEXT_V1,
                    xkb::KEYMAP_COMPILE_NO_FLAGS,
                ) {
                    state.xkb_state = Some(xkb::State::new(&km));
                    state.xkb_keymap = Some(km);
                }
            }
            zwp_input_method_keyboard_grab_v2::Event::Key {
                key,
                state: ks,
                time,
                ..
            } => match ks {
                WEnum::Value(wl_keyboard::KeyState::Pressed) => {
                    state.handle_key_press(key, time, qh);
                }
                WEnum::Value(wl_keyboard::KeyState::Released) => {
                    state.handle_key_release(key, time, qh);
                }
                _ => {}
            },
            zwp_input_method_keyboard_grab_v2::Event::Modifiers {
                mods_depressed,
                mods_latched,
                mods_locked,
                group,
                ..
            } => {
                // Update virtual keyboard modifier state so Ctrl+C etc. are delivered correctly.
                if let Some(vk) = &state.vk {
                    vk.modifiers(mods_depressed, mods_latched, mods_locked, group);
                }
                if let Some(xs) = &mut state.xkb_state {
                    xs.update_mask(mods_depressed, mods_latched, mods_locked, 0, 0, group);
                    let mut m = 0u32;
                    if xs.mod_name_is_active(xkb::MOD_NAME_SHIFT, xkb::STATE_MODS_EFFECTIVE) {
                        m |= MOD_SHIFT;
                    }
                    if xs.mod_name_is_active(xkb::MOD_NAME_CTRL, xkb::STATE_MODS_EFFECTIVE) {
                        m |= MOD_CONTROL;
                    }
                    if xs.mod_name_is_active(xkb::MOD_NAME_ALT, xkb::STATE_MODS_EFFECTIVE) {
                        m |= MOD_MOD1;
                    }
                    state.mods = m;
                }
            }
            _ => {}
        }
    }
}

impl Dispatch<ZwpInputPopupSurfaceV2, ()> for App {
    fn event(
        _s: &mut Self,
        _p: &ZwpInputPopupSurfaceV2,
        _e: zwp_input_popup_surface_v2::Event,
        _: &(),
        _c: &Connection,
        _q: &QueueHandle<Self>,
    ) {
    }
}

delegate_noop!(App: ignore WlCompositor);
delegate_noop!(App: ignore WlShm);
delegate_noop!(App: ignore WlShmPool);
delegate_noop!(App: ignore WlBuffer);
delegate_noop!(App: ignore WlSurface);
delegate_noop!(App: ignore WlSeat);
delegate_noop!(App: ignore WlKeyboard);
delegate_noop!(App: ignore ZwpInputMethodManagerV2);
delegate_noop!(App: ignore ZwpVirtualKeyboardManagerV1);
delegate_noop!(App: ignore ZwpVirtualKeyboardV1);

fn memfd() -> std::io::Result<File> {
    let name = c"keytao-shm";
    let fd = unsafe { libc::memfd_create(name.as_ptr(), libc::MFD_CLOEXEC) };
    if fd < 0 {
        return Err(std::io::Error::last_os_error());
    }
    Ok(unsafe { File::from_raw_fd(fd) })
}

// ── System font discovery ─────────────────────────────────────────────────────
// cosmic-text uses fontconfig internally (via fontdb) and loads ALL system fonts
// automatically, including NotoColorEmoji (CBDT) and NotoSansCJK. No manual
// font loading is needed — FontSystem::new() picks them all up via fc-list/fontdb.
