//! Shared librime engine wrapper.

use keytao_core::{default_shared_data_dir, default_user_data_dir, deploy, Engine, ImeState};
use std::{
    path::{Path, PathBuf},
    sync::{Arc, Mutex},
};

// Schemas keytao-ime activates. Kept in sync with the installer's default.custom.yaml.
const DEFAULT_CUSTOM_YAML: &str = r#"# default.custom.yaml — generated by keytao-ime
patch:
  schema_list:
    - schema: keytao
    - schema: keytao-dz
    - schema: keytao-bj
  menu:
    page_size: 6
  ascii_composer/good_old_caps_lock: true
  ascii_composer/switch_key:
    Caps_Lock: commit_text
    Shift_L: commit_text
"#;

#[derive(Clone)]
pub struct CoreEngine(Arc<Mutex<Option<Engine>>>);

impl CoreEngine {
    pub fn new() -> Self {
        Self(Arc::new(Mutex::new(None)))
    }

    pub fn init(&self) -> Result<(), String> {
        // Prefer fcitx5/rime dir when it has fully compiled binaries — avoids a
        // slow recompile and fixes missing keytao.extended.{table,reverse}.bin.
        // keytao-ime and fcitx5 cannot run simultaneously on Wayland anyway.
        let user_dir = preferred_user_dir().ok_or("cannot determine keytao data directory")?;
        let user = user_dir.to_string_lossy().into_owned();
        let shared = default_shared_data_dir();

        // librime only reads *.custom.yaml from user_data_dir, not shared_data_dir.
        // Ensure default.custom.yaml exists before deploy() so the schema list is compiled.
        ensure_default_custom_yaml(&user_dir)?;

        deploy(user.clone(), shared)?;
        let engine = Engine::new()?;
        *self.0.lock().unwrap() = Some(engine);
        Ok(())
    }

    pub fn process_key(&self, keycode: u32, mask: u32) -> Option<ImeState> {
        self.0
            .lock()
            .unwrap()
            .as_ref()
            .map(|e| e.process_key(keycode, mask))
    }

    pub fn select_candidate(&self, index: usize) -> Option<ImeState> {
        self.0
            .lock()
            .unwrap()
            .as_ref()
            .map(|e| e.select_candidate(index))
    }

    pub fn change_page(&self, backward: bool) -> Option<ImeState> {
        self.0
            .lock()
            .unwrap()
            .as_ref()
            .map(|e| e.change_page(backward))
    }

    pub fn reset(&self) -> Option<ImeState> {
        self.0.lock().unwrap().as_ref().map(|e| e.reset())
    }
}

fn ensure_default_custom_yaml(user_dir: &Path) -> Result<(), String> {
    let target = user_dir.join("default.custom.yaml");
    if target.exists() {
        return Ok(());
    }
    std::fs::create_dir_all(user_dir).map_err(|e| format!("create user dir: {e}"))?;
    std::fs::write(&target, DEFAULT_CUSTOM_YAML)
        .map_err(|e| format!("write default.custom.yaml: {e}"))?;
    Ok(())
}

/// Use fcitx5/rime dir when its build has compiled table binaries (avoids recompile).
/// Falls back to the dedicated keytao dir otherwise.
fn preferred_user_dir() -> Option<PathBuf> {
    let fcitx5 = dirs::data_local_dir()?.join("fcitx5/rime");
    if fcitx5
        .join("build")
        .join("keytao.extended.table.bin")
        .exists()
    {
        return Some(fcitx5);
    }
    default_user_data_dir()
}
